Repository gwpy/gwpy, pull requests merged in 2023-11, with the labels that each got.

#1710 Run apt-get update before apt-get install in CI jobs
  .github/workflows/dependencies.yml
Labels: continuous-integration

#1715 Avoid python-framel 8.46.0
  pyproject.toml
Labels: api:patch, build:conda

#1718 Remove all use of distutils
  gwpy/testing/utils.py
  gwpy/utils/shell.py
  gwpy/utils/tests/test_shell.py
Labels: api:patch, gwpy.utils, gwpy.testing

#1713 track LALSuite rebrand in docs
  docs/overview.rst
Labels: documentation

#1712 Drop `HAS_TEX` for faster startup time
  gwpy/plot/tests/test_tex.py
  gwpy/plot/tex.py
  gwpy/testing/fixtures.py
Labels: dep:matplotlib, api:patch, gwpy.plot, performance
